[toolchain]
# Stable
channel = "1.77.0" # rustc 1.77.0 (aedd173a2 2024-03-21)
# Nightly
#channel    = "nightly-2024-01-22" # rustc 1.77.0-nightly (ef71f1047 2024-01-21)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile    = "minimal"
targets    = ["wasm32-unknown-unknown"]
