#[toolchain]
#channel = "nightly-2024-01-01"
#components = [
#	"cargo",
#	"clippy",
#	"rust-analyzer",
#	"rust-src",
#	"rust-std",
#	"rustc-dev",
#	"rustc",
#	"rustfmt",
#]
#targets = [ "wasm32-unknown-unknown" ]
#profile = "minimal"

[toolchain]
# Stable
#channel = "1.68.2" # rustc 1.68.2 (9eb3afe9e 2023-03-27)
# Nightly
channel = "nightly-2024-10-25" # rustc 1.67.5-nightly (a00f8ba7f 2022-11-15)
#components = ["rustfmt", "clippy"]
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"